/*
-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ COMMON START
-- DROP SEQ
DROP SEQUENCE SEQ_IAAP_CM_DIRECTORY_GROUP;
DROP SEQUENCE SEQ_IAAP_CM_DIRECTORY;
DROP SEQUENCE SEQ_IAAP_STT_TRAIN_DATA;
DROP SEQUENCE SEQ_IAAP_STT_TRAIN_AM_DATA;
DROP SEQUENCE SEQ_IAAP_STT_SERVICE_MODEL;
DROP SEQUENCE SEQ_IAAP_STT_ENGINE_URL;
DROP SEQUENCE SEQ_IAAP_STT_VERIFY_DATASET;
DROP SEQUENCE SEQ_IAAP_STT_VERIFY_DATA;
DROP SEQUENCE SEQ_IAAP_STT_VERIFY_HISTORY;
DROP SEQUENCE SEQ_IAAP_STT_LOG;
DROP SEQUENCE SEQ_IAAP_STT_DICTATION;
DROP SEQUENCE SEQ_IAAP_STT_USAGE;
DROP SEQUENCE SEQ_IAAP_STT_DEPLOY_MODEL;
DROP SEQUENCE SEQ_IAAP_STT_DEPLOY_MNG;
DROP SEQUENCE SEQ_IAAP_STT_TRAIN_MNG;
DROP SEQUENCE SEQ_IAAP_STT_CONFIG;
DROP SEQUENCE SEQ_IAAP_STT_CALL_INFO;
DROP SEQUENCE SEQ_IAAP_STT_RESULT_INFO;
DROP SEQUENCE SEQ_IAAP_STT_TRAIN_DATASET;

-- DROP TABLE
DROP TABLE IAAP_CM_DIRECTORY_GROUP;
DROP TABLE IAAP_CM_DIRECTORY;
DROP TABLE IAAP_STT_TRAIN_DATA;
DROP TABLE IAAP_STT_TRAIN_AM_DATA;
DROP TABLE IAAP_STT_SERVICE_MODEL;
DROP TABLE IAAP_STT_ENGINE_URL;
DROP TABLE IAAP_STT_VERIFY_DATASET;
DROP TABLE IAAP_STT_VERIFY_DATA;
DROP TABLE IAAP_STT_VERIFY_HISTORY;
DROP TABLE IAAP_STT_LOG;
DROP TABLE IAAP_STT_DICTATION;
DROP TABLE IAAP_STT_USAGE;
DROP TABLE IAAP_STT_TRAIN_MNG;
DROP TABLE IAAP_STT_DEPLOY_MNG;
DROP TABLE IAAP_STT_DEPLOY_MODEL;
DROP TABLE IAAP_STT_TEST_DATA;
DROP TABLE IAAP_STT_STATISTICS;
DROP TABLE IAAP_STT_STATISTICS_ERROR;
DROP TABLE IAAP_STT_CONFIG;
DROP TABLE IAAP_STT_RESULT_INFO;
DROP TABLE IAAP_STT_CALL_INFO;
DROP TABLE IAAP_STT_TRAIN_DATASET;
*/

-- CREATE TABLE
CREATE TABLE IAAP_CM_DIRECTORY_GROUP
(
    ID          NUMBER(11)    NOT NULL PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(256),
    REG_DT      DATE          DEFAULT CURRENT_TIMESTAMP,
    REG_ID      VARCHAR2(100),
    REG_IP      VARCHAR2(100) NOT NULL,
    UPD_DT      DATE          DEFAULT CURRENT_TIMESTAMP,
    UPD_ID      VARCHAR2(100),
    UPD_IP      VARCHAR2(100) NOT NULL,
    USE_YN      VARCHAR2(1)   DEFAULT 'Y',
    PATH_GUBUN      VARCHAR2(20),
    HOME_PATH      VARCHAR2(20) 
);

COMMENT ON TABLE IAAP_CM_DIRECTORY_GROUP IS '디렉토리 그룹';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.ID IS '디렉토리 그룹 ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.NAME IS '디렉토리 그룹명';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.DESCRIPTION IS '디렉토리 그룹 설명';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.USE_YN IS '사용여부';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.PATH_GUBUN IS '데이터셋 구분용(학습TRAIN,검증VERIFY)';
COMMENT ON COLUMN IAAP_CM_DIRECTORY_GROUP.HOME_PATH IS '데이터셋의 루트경로';


-- CREATE TABLE
CREATE TABLE IAAP_CM_DIRECTORY
(
    ID          NUMBER(11) NOT NULL,
    NAME        VARCHAR2(100) NOT NULL,
    HOME_PATH   VARCHAR2(500) NOT NULL,
    PATH        VARCHAR2(500) NOT NULL,
    PRIORITY    NUMBER(11) NOT NULL,
    IN_USE      VARCHAR2(1)   NOT NULL,
    GROUP_ID    NUMBER(11) NOT NULL,
    REG_DT      DATE DEFAULT SYSDATE NOT NULL,
    REG_ID      VARCHAR2(100),
    REG_IP      VARCHAR2(100) NOT NULL,
    UPD_DT      DATE DEFAULT SYSDATE NOT NULL,
    UPD_ID      VARCHAR2(100),
    UPD_IP      VARCHAR2(100) NOT NULL,
    USE_YN      VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_CM_DIRECTORY IS '디렉토리';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.ID IS '디렉토리 ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.NAME IS '디렉토리명';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.HOME_PATH IS '디렉토리 홈 경로';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.PATH IS '디렉토리 경로';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.PRIORITY IS '노출순서';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.IN_USE IS '노출여부';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.GROUP_ID IS '그룹ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_CM_DIRECTORY.USE_YN IS '사용여부';

-- CREATE SEQ
CREATE SEQUENCE SEQ_IAAP_CM_DIRECTORY_GROUP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_CM_DIRECTORY START WITH 1 INCREMENT BY 1;

-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ COMMON END

-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ STT START

-- CREATE TABLE
CREATE TABLE IAAP_STT_TRAIN_DATA
(
    ID                  NUMBER(10)      NOT NULL,
    DATA_TYPE           VARCHAR2(20)  NOT NULL,
    SERVICE_MODEL       VARCHAR2(100),
    SERVICE_MODEL_ID    NUMBER(11) NOT NULL,
    CONTENTS            VARCHAR2(255) NOT NULL,
    REPEAT_COUNT        NUMBER(10) DEFAULT 1      NOT NULL,
    DESCRIPTION         VARCHAR2(255) DEFAULT NULL,
    REG_DT              DATE DEFAULT  SYSDATE     NOT NULL,
    REG_ID              VARCHAR2(60)  NOT NULL,
    REG_IP              VARCHAR2(23)  NOT NULL,
    UPD_DT              DATE    	  DEFAULT NULL,
    UPD_ID              VARCHAR2(60)  DEFAULT NULL,
    UPD_IP              VARCHAR2(23)  DEFAULT NULL,
    USE_YN              CHAR(1) DEFAULT 'Y'      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IAAP_STT_TRAIN_DATA_UK UNIQUE (SERVICE_MODEL_ID, CONTENTS)
);

COMMENT ON TABLE IAAP_STT_TRAIN_DATA IS 'STT 학습데이터 관리 테이블';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.ID IS '학습데이터ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.DATA_TYPE IS '데이터구분';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.SERVICE_MODEL IS '서비스모델';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.SERVICE_MODEL_ID IS '서비스모델 ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.CONTENTS IS '데이터';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.REPEAT_COUNT IS '가중치';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.REG_DT IS '등록일시';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.UPD_DT IS '수정일시';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_TRAIN_DATA.USE_YN IS '사용여부';


CREATE TABLE IAAP_STT_TRAIN_AM_DATA
(	
	AM_DATA_ID NUMBER(10,0) NOT NULL ENABLE, 
	MODEL_TYPE VARCHAR2(20) NOT NULL ENABLE, 
	SERVICE_MODEL VARCHAR2(20), 
	SERVICE_MODEL_ID NUMBER(11,0) NOT NULL ENABLE, 
	ANS_DATASET_NM VARCHAR2(50) NOT NULL ENABLE, 
	TRAIN_VOICE_CNT NUMBER(11,0), 
	DESCRIPTION VARCHAR2(100),
    DATA_SOURCE NUMBER(11,0),
	ANS_FILE VARCHAR2(100), 
	VOICE_FILE VARCHAR2(100), 
	AM_DATA_PATH VARCHAR2(100), 
	REG_DT DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	REG_ID VARCHAR2(60) NOT NULL ENABLE, 
	REG_IP VARCHAR2(23) NOT NULL ENABLE, 
	UPD_DT DATE, 
	UPD_ID VARCHAR2(60), 
	UPD_IP VARCHAR2(23), 
	BASE_PATH VARCHAR2(50), 
	DETAIL_PATH VARCHAR2(20), 
	USE_YN CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
    FIRST_PATH_YN CHAR(1)
   );
-- SEGMENT CREATION DEFERRED
-- PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
-- NOCOMPRESS LOGGING
-- TABLESPACE "USERS" ;

COMMENT ON TABLE IAAP_STT_TRAIN_AM_DATA IS 'STT AM 학습데이터 관리테이블';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.AM_DATA_ID IS 'AM학습데이터ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.MODEL_TYPE IS '학습데이터 모델타입';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.SERVICE_MODEL IS '서비스모델';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.SERVICE_MODEL_ID IS '서비스모델ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.ANS_DATASET_NM IS '정답지 데이터셋이름';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.TRAIN_VOICE_CNT IS '학습음성갯수';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.DATA_SOURCE IS '데이터 출처 여부(일반 : 1, 전사 : 2)';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.ANS_FILE IS '정답지파일명';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.VOICE_FILE IS '음성파일명';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.AM_DATA_PATH IS 'AM학습데이터 경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.REG_DT IS '등록일시';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.REG_ID IS '등록자ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.REG_IP IS '등록자IP';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.UPD_DT IS '수정일시';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.UPD_ID IS '수정자ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.UPD_IP IS '수정자IP';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.USE_YN IS '사용여부';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.BASE_PATH IS '학습데이터셋의 기본 경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.DETAIL_PATH IS '학습데이터셋의 하위 경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_AM_DATA.FIRST_PATH_YN IS '초기 대량 데이터 경로 여부';

CREATE TABLE IAAP_STT_SERVICE_MODEL
(
    ID                   NUMBER(11) NOT NULL,
    SERVICE_MODEL_NAME   VARCHAR2(100) NOT NULL,
    SERVICE_CODE         VARCHAR2(100) NOT NULL,
    DESCRIPTION          VARCHAR2(256),
    REG_DT               DATE     DEFAULT SYSDATE,
    REG_ID               VARCHAR2(100) NOT NULL,
    REG_IP               VARCHAR2(100) NOT NULL,
    UPD_DT               DATE     DEFAULT NULL,
    UPD_ID               VARCHAR2(60)  DEFAULT NULL,
    UPD_IP               VARCHAR2(23)  DEFAULT NULL,
    USE_YN               CHAR(1) DEFAULT 'Y'      NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_SERVICE_MODEL IS 'STT 서비스모델 관리 테이블';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.ID IS '서비스모델 ID';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.SERVICE_MODEL_NAME IS '서비스모델명';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.SERVICE_CODE IS '서비스코드';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.UPD_DT IS '수정일시';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_SERVICE_MODEL.USE_YN IS '사용여부';

CREATE TABLE IAAP_STT_ENGINE_URL
(
    ID                   NUMBER(11) NOT NULL,
    TENANT_NAME          VARCHAR2(100) NOT NULL,
    ENGINE_URL           VARCHAR2(100) NOT NULL,
    DESCRIPTION          VARCHAR2(256),
    REG_DT               DATE     DEFAULT SYSDATE,
    REG_ID               VARCHAR2(100) NOT NULL,
    REG_IP               VARCHAR2(100) NOT NULL,
    UPD_DT               DATE     DEFAULT NULL,
    UPD_ID               VARCHAR2(60)  DEFAULT NULL,
    UPD_IP               VARCHAR2(23)  DEFAULT NULL,
    USE_YN               CHAR(1) DEFAULT 'Y'      NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_ENGINE_URL IS 'STT 엔진 URL 관리 테이블';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.ID IS '엔진 URL ID';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.TENANT_NAME IS '테넌트명';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.ENGINE_URL IS 'URL';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.UPD_DT IS '수정일시';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_ENGINE_URL.USE_YN IS '사용여부';

CREATE TABLE IAAP_STT_VERIFY_DATASET
(
    ID                  NUMBER(11) NOT NULL,
    SERVICE_MODEL_ID    NUMBER(11) NOT NULL,
    DIRECTORY_ID        NUMBER(11) NOT NULL,
    NAME                VARCHAR2(100) NOT NULL,
    DESCRIPTION         VARCHAR2(255),
    REG_DT              DATE DEFAULT SYSDATE     NOT NULL,
    REG_ID              VARCHAR2(100) NOT NULL,
    REG_IP              VARCHAR2(100) NOT NULL,
    UPD_DT              DATE DEFAULT SYSDATE     NOT NULL,
    UPD_ID              VARCHAR2(100) NOT NULL,
    UPD_IP              VARCHAR2(100) NOT NULL,
    USE_YN              VARCHAR2(1) DEFAULT 'Y'   NOT NULL,
    FIRST_PATH_YN       VARCHAR2(1),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_VERIFY_DATASET IS '검증데이터셋';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.ID IS '검증데이터셋 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.SERVICE_MODEL_ID IS '서비스모델 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.DIRECTORY_ID IS '디렉토리 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.NAME IS '검증데이터셋 이름';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.USE_YN IS '사용여부';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATASET.FIRST_PATH_YN IS '초기 대량 데이터 경로 여부';

CREATE TABLE IAAP_STT_VERIFY_DATA
(
    ID              NUMBER(11) NOT NULL,
    DATASET_ID      NUMBER(11) NOT NULL,
    WAV_FILE_NAME   VARCHAR2(500) NOT NULL,
    ANSWER_FILE_NAME   VARCHAR2(500) ,
    DICTATED_TEXT   CLOB     NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    REG_DT          DATE DEFAULT SYSDATE     NOT NULL,
    REG_ID          VARCHAR2(100) NOT NULL,
    REG_IP          VARCHAR2(100) NOT NULL,
    UPD_DT          DATE DEFAULT SYSDATE     NOT NULL,
    UPD_ID          VARCHAR2(100) NOT NULL,
    UPD_IP          VARCHAR2(100) NOT NULL,
    USE_YN          VARCHAR2(1) DEFAULT 'Y'   NOT NULL,
    DATASET_NAME   VARCHAR2(50),
    SERVICE_MODEL_ID    NUMBER(11),
    BASE_PATH   VARCHAR2(50),
    DETAIL_PATH   VARCHAR2(20),
    VERIFY_DATA_PATH   VARCHAR2(100),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_VERIFY_DATA IS '검증데이터';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.ID IS '검증데이터 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.DATASET_ID IS '검증데이터셋 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.WAV_FILE_NAME IS '음원파일명';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.ANSWER_FILE_NAME IS '정답지파일명';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.DICTATED_TEXT IS '전사한 텍스트';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.USE_YN IS '사용여부';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.DATASET_NAME IS '검증데이터셋 이름';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.SERVICE_MODEL_ID IS '서비스모델ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.BASE_PATH IS '학습데이터셋의 기본 경로';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.DETAIL_PATH IS '학습데이터셋의 하위 경로';
COMMENT ON COLUMN IAAP_STT_VERIFY_DATA.VERIFY_DATA_PATH IS '검증데이터 최종경로';

CREATE TABLE IAAP_STT_VERIFY_HISTORY
(
    ID                  NUMBER(11)    NOT NULL,
    DATASET_ID          NUMBER(11)    NOT NULL,
    DEPLOY_ID           NUMBER(11)    NOT NULL,
    STATUS              VARCHAR2(100)    NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    START_AT            DATE,
    END_AT              DATE,
    CER                 BINARY_DOUBLE,
    WER                 BINARY_DOUBLE,
    FAIL_CAUSE          VARCHAR2(500),
    REG_DT              DATE DEFAULT SYSDATE        NOT NULL,
    REG_ID              VARCHAR2(100)    NOT NULL,
    REG_IP              VARCHAR2(100)    NOT NULL,
    UPD_DT              DATE DEFAULT SYSDATE        NOT NULL,
    UPD_ID              VARCHAR2(100)    NOT NULL,
    UPD_IP              VARCHAR2(100)    NOT NULL,
    USE_YN              VARCHAR2(1) DEFAULT 'Y'      NOT NULL,
    SERVICE_MODEL_ID    NUMBER(11)    NOT NULL,
    VERSION             VARCHAR2(100)    NOT NULL,
    SAVE_YN	            VARCHAR2(1) DEFAULT 'N',
    DATASET_NAME	    VARCHAR2(50),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_VERIFY_HISTORY IS '검증이력';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.ID IS '검증이력 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.DATASET_ID IS '검증데이터셋 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.DEPLOY_ID IS '배포 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.STATUS IS '검증상태';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.START_AT IS '요청시간';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.END_AT IS '종료시간';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.CER IS 'CER';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.WER IS 'WER';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.FAIL_CAUSE IS '실패원인';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.USE_YN IS '사용여부';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.SERVICE_MODEL_ID IS '서비스 모델 아이디';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.VERSION IS '버전';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.SAVE_YN IS '인식률 반영 여부';
COMMENT ON COLUMN IAAP_STT_VERIFY_HISTORY.DATASET_NAME IS '검증데이터셋 이름';

CREATE TABLE IAAP_STT_LOG
(
    ID                  NUMBER(11) NOT NULL,
    CALL_KEY            VARCHAR2(500)    NOT NULL,
    CUSTOMER_IDENTIFIER VARCHAR2(500)    NOT NULL,
    DIRECTION           VARCHAR2(100)    NOT NULL,
    START_AT            TIMESTAMP        NOT NULL,
    END_AT              TIMESTAMP        NULL,
    START_TIME          NUMBER(11) default 0 NOT NULL,
    END_TIME            NUMBER(11) default 0 NOT NULL,
    WAV_FILE_PATH       VARCHAR2(500)    NOT NULL,
    SERVICE_MODEL_ID    NUMBER(11)    NOT NULL,
    ASSISTANT_ID        VARCHAR2(100),
    STATUS              VARCHAR2(100)    NOT NULL,
    FAIL_CAUSE          VARCHAR2(500),
    TRANSCRIPT          CLOB        NOT NULL,
    TRANSCRIPT_START    NUMBER(11)    NOT NULL,
    TRANSCRIPT_END      NUMBER(11)    NOT NULL,
    CER                 BINARY_DOUBLE          NOT NULL,
    SENTENCE_WAV_PATH	VARCHAR2(500),
  	WORDS				CLOB,
    USED_AS_DICTATION   VARCHAR2(1) DEFAULT 'N'      NOT NULL,
    USE_YN              VARCHAR2(1) DEFAULT 'Y'      NOT NULL,
    PRIMARY KEY (ID)
) PARTITION BY RANGE (START_AT) (
        PARTITION IAAP_STT_LOG_202309 VALUES LESS THAN ('2023-10-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202310 VALUES LESS THAN ('2023-11-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202311 VALUES LESS THAN ('2023-12-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202312 VALUES LESS THAN ('2024-01-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202401 VALUES LESS THAN ('2024-02-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202402 VALUES LESS THAN ('2024-03-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202403 VALUES LESS THAN ('2024-04-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202404 VALUES LESS THAN ('2024-05-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202405 VALUES LESS THAN ('2024-06-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202406 VALUES LESS THAN ('2024-07-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202407 VALUES LESS THAN ('2024-08-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202408 VALUES LESS THAN ('2024-09-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202409 VALUES LESS THAN ('2024-10-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202410 VALUES LESS THAN ('2024-11-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202411 VALUES LESS THAN ('2024-12-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202412 VALUES LESS THAN ('2025-01-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202501 VALUES LESS THAN ('2025-02-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202502 VALUES LESS THAN ('2025-03-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202503 VALUES LESS THAN ('2025-04-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202504 VALUES LESS THAN ('2025-05-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202505 VALUES LESS THAN ('2025-06-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202506 VALUES LESS THAN ('2025-07-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202507 VALUES LESS THAN ('2025-08-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202508 VALUES LESS THAN ('2025-09-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202509 VALUES LESS THAN ('2025-10-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202510 VALUES LESS THAN ('2025-11-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202511 VALUES LESS THAN ('2025-12-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202512 VALUES LESS THAN ('2026-01-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202601 VALUES LESS THAN ('2026-02-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202602 VALUES LESS THAN ('2026-03-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202603 VALUES LESS THAN ('2026-04-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202604 VALUES LESS THAN ('2026-05-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202605 VALUES LESS THAN ('2026-06-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202606 VALUES LESS THAN ('2026-07-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202607 VALUES LESS THAN ('2026-08-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202608 VALUES LESS THAN ('2026-09-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202609 VALUES LESS THAN ('2026-10-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202610 VALUES LESS THAN ('2026-11-01 00:00:00'),
        PARTITION IAAP_STT_LOG_202611 VALUES LESS THAN ('2026-12-01 00:00:00'),
        PARTITION PMAXVALUES VALUES LESS THAN (MAXVALUE)
);

COMMENT ON TABLE IAAP_STT_LOG IS 'STT 결과로그';
COMMENT ON COLUMN IAAP_STT_LOG.ID IS '로그 ID';
COMMENT ON COLUMN IAAP_STT_LOG.CALL_KEY IS '콜키';
COMMENT ON COLUMN IAAP_STT_LOG.CUSTOMER_IDENTIFIER IS '고객 식별정보';
COMMENT ON COLUMN IAAP_STT_LOG.DIRECTION IS 'TXRX';
COMMENT ON COLUMN IAAP_STT_LOG.START_AT IS '수신 시간';
COMMENT ON COLUMN IAAP_STT_LOG.END_AT IS '사용 안함';
COMMENT ON COLUMN IAAP_STT_LOG.START_TIME IS '콜/턴 시작시간';
COMMENT ON COLUMN IAAP_STT_LOG.END_TIME IS '콜/턴 종료시간';
COMMENT ON COLUMN IAAP_STT_LOG.WAV_FILE_PATH IS '음원파일 경로';
COMMENT ON COLUMN IAAP_STT_LOG.SERVICE_MODEL_ID IS '서비스모델 ID';
COMMENT ON COLUMN IAAP_STT_LOG.ASSISTANT_ID IS '상담사 ID';
COMMENT ON COLUMN IAAP_STT_LOG.STATUS IS '성공 실패 여부';
COMMENT ON COLUMN IAAP_STT_LOG.FAIL_CAUSE IS '실패여부';
COMMENT ON COLUMN IAAP_STT_LOG.TRANSCRIPT IS 'STT 결과(문장)';
COMMENT ON COLUMN IAAP_STT_LOG.TRANSCRIPT_START IS 'STT 결과(문장) 시작 오프셋';
COMMENT ON COLUMN IAAP_STT_LOG.TRANSCRIPT_END IS 'STT 결과(문장) 끝 오프셋';
COMMENT ON COLUMN IAAP_STT_LOG.CER IS '신뢰도(CER)';
COMMENT ON COLUMN IAAP_STT_LOG.SENTENCE_WAV_PATH IS '발화단위의 음성 경로';
COMMENT ON COLUMN IAAP_STT_LOG.WORDS IS 'word 단위 신뢰도 정보';
COMMENT ON COLUMN IAAP_STT_LOG.USED_AS_DICTATION IS '전사데이터 등록여부';
COMMENT ON COLUMN IAAP_STT_LOG.USE_YN IS '사용여부';

CREATE TABLE IAAP_STT_DICTATION
(
    ID                  NUMBER(19)       NOT NULL,
    STT_LOG_ID	NUMBER(11)	NOT NULL,
    TRANSCRIPT          CLOB     NOT NULL,
    WAV_FILE_PATH       VARCHAR2(500) NOT NULL,
    SERVICE_MODEL_ID    NUMBER(11) NOT NULL,
    DIRECTION           VARCHAR2(100) NOT NULL,
    DICTATED_TEXT       CLOB,
    USAGE_TYPE          VARCHAR2(100) DEFAULT 'NONE' NOT NULL,
    IS_PREEMPTED        VARCHAR2(1) DEFAULT 'N'   NOT NULL,
    REG_DT              DATE DEFAULT SYSDATE     NOT NULL,
    REG_ID              VARCHAR2(100) NOT NULL,
    REG_IP              VARCHAR2(100) NOT NULL,
    UPD_DT              DATE DEFAULT SYSDATE     NOT NULL,
    UPD_ID              VARCHAR2(100) NOT NULL,
    UPD_IP              VARCHAR2(100) NOT NULL,
    USE_YN              VARCHAR2(1) DEFAULT 'Y'   NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IAAP_STT_DICATION_UK UNIQUE (WAV_FILE_PATH)
);

COMMENT ON TABLE IAAP_STT_DICTATION IS '전사데이터';
COMMENT ON COLUMN IAAP_STT_DICTATION.ID IS '전사데이터 ID';
COMMENT ON COLUMN IAAP_STT_DICTATION.STT_LOG_ID IS 'STT 결과 ID';
COMMENT ON COLUMN IAAP_STT_DICTATION.TRANSCRIPT IS 'STT 결과';
COMMENT ON COLUMN IAAP_STT_DICTATION.WAV_FILE_PATH IS '음원파일 경로';
COMMENT ON COLUMN IAAP_STT_DICTATION.SERVICE_MODEL_ID IS '서비스타입';
COMMENT ON COLUMN IAAP_STT_DICTATION.DIRECTION IS 'TXRX 구분';
COMMENT ON COLUMN IAAP_STT_DICTATION.DICTATED_TEXT IS '전사데이터';
COMMENT ON COLUMN IAAP_STT_DICTATION.USAGE_TYPE IS '데이터구분 AM 학습데이터 혹은 검증데이터';
COMMENT ON COLUMN IAAP_STT_DICTATION.IS_PREEMPTED IS '현재 수정중 여부(Y: 수정중, N: 수정중 아님)';
COMMENT ON COLUMN IAAP_STT_DICTATION.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_DICTATION.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_DICTATION.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_DICTATION.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_DICTATION.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_DICTATION.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_DICTATION.USE_YN IS '사용여부';

CREATE TABLE IAAP_STT_USAGE
(
    ID                          NUMBER(11) NOT NULL,
    DICTATION_ID                NUMBER(11) NOT NULL,
    VERIFY_DATASET_ID           NUMBER(11),
    AM_TRAIN_DATA_DIRECTORY_ID  NUMBER(11),
    AM_DATA_PATH                VARCHAR2(100),
    WAV_FILE_NAME               VARCHAR2(100),
    TYPE                        VARCHAR2(100),
    REG_DT                      DATE DEFAULT SYSDATE     NOT NULL,
    REG_ID                      VARCHAR2(100) NOT NULL,
    REG_IP                      VARCHAR2(100) NOT NULL,
    UPD_DT                      DATE              DEFAULT SYSDATE,
    UPD_ID                      VARCHAR2(100) NOT NULL,
    UPD_IP                      VARCHAR2(100) NOT NULL,
    USE_YN                      VARCHAR2(1) DEFAULT 'Y'   NOT NULL,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_USAGE IS '전사데이터 데이터구분';
COMMENT ON COLUMN IAAP_STT_USAGE.ID IS '데이터구분 ID';
COMMENT ON COLUMN IAAP_STT_USAGE.DICTATION_ID IS '전사데이터 ID';
COMMENT ON COLUMN IAAP_STT_USAGE.VERIFY_DATASET_ID IS '검증데이터셋 ID';
COMMENT ON COLUMN IAAP_STT_USAGE.AM_TRAIN_DATA_DIRECTORY_ID IS 'AM 학습데이터 음원파일 저장 경로 ID';
COMMENT ON COLUMN IAAP_STT_USAGE.AM_DATA_PATH IS 'AM 학습데이터 저장 경로';
COMMENT ON COLUMN IAAP_STT_USAGE.WAV_FILE_NAME IS '검증 음원파일 이름';
COMMENT ON COLUMN IAAP_STT_USAGE.TYPE IS '데이터구분 AM 학습데이터 혹은 검증데이터';
COMMENT ON COLUMN IAAP_STT_USAGE.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_USAGE.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_USAGE.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_USAGE.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_USAGE.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_USAGE.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_USAGE.USE_YN IS '사용여부';

-- 학습이력
CREATE TABLE IAAP_STT_TRAIN_MNG
(
    ID              NUMBER(11) NOT NULL,
    SERVICE_MODEL_ID   NUMBER(10)       NOT NULL,
    DESCRIPTION     VARCHAR2(256),
    UPDATED_BY      VARCHAR2(256) NOT NULL,
    REQUESTED_AT    DATE     NOT NULL,
    COMPLETED_AT    DATE,
    DURATION        NUMBER(10),
    DATA_NUM        NUMBER(11) NOT NULL,
    DATA_TIME       VARCHAR2(256) ,
    RESULT_MODEL_ID VARCHAR2(256) NOT NULL,
    RESULT_CODE     VARCHAR2(100),
    RESULT_MSG      VARCHAR2(256),
    REG_DT          DATE DEFAULT SYSDATE,
    REG_ID          VARCHAR2(100) NOT NULL,
    REG_IP          VARCHAR2(100) NOT NULL,
    UPD_DT          DATE DEFAULT SYSDATE,
    UPD_ID          VARCHAR2(100) NOT NULL,
    UPD_IP          VARCHAR2(100) NOT NULL,
    STATUS          VARCHAR2(256),
    MODEL_TYPE         VARCHAR2(256),
    MODEL_PATH      VARCHAR2(256),
    MODEL_AUTH_KEY  VARCHAR2(256),
    TRAIN_DATA_PATH VARCHAR2(256),
    USE_YN          VARCHAR2(2)   NOT NULL,
    E2EUSL_WAVPATH_LIST VARCHAR2(256), 
	E2ESL_DATAPATH_LIST VARCHAR2(256), 
	E2ESL_WAVPATH_LIST VARCHAR2(256),
	AM_DATASET_LIST VARCHAR2(256),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_TRAIN_MNG IS '학습이력';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.ID IS '학습이력ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.SERVICE_MODEL_ID IS '서비스모델ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.UPDATED_BY IS '작성자';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.REQUESTED_AT IS '학습일시';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.COMPLETED_AT IS '학습완료일시';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.DURATION IS '소요시간';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.DATA_NUM IS '학습데이터수';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.DATA_TIME IS '음성데이터 총 학습시간';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.RESULT_MODEL_ID IS '결과모델ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.RESULT_CODE IS '학습결과코드';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.RESULT_MSG IS '학습요청결과';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.STATUS IS '학습상태';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.MODEL_TYPE IS '학습요청한 LM TYPE';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.MODEL_PATH IS '학습된 모델 저장경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.MODEL_AUTH_KEY IS 'MD5 hash checksum';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.TRAIN_DATA_PATH IS '학습데이터 저장 경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.E2ESL_DATAPATH_LIST IS 'E2ESL,E2EMSL타입의 경우 사용하는 정답지 파일경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.E2ESL_WAVPATH_LIST IS 'E2ESL,E2EMSL타입의 경우 사용하는 지도 학습음성 파일경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.E2EUSL_WAVPATH_LIST IS 'E2EUSL,E2EMSL타입의 경우 사용하는 비지도 학습음성 파일경로';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.AM_DATASET_LIST IS 'AM학습데이터 등록시  저장되는 데이터셋 목록';
COMMENT ON COLUMN IAAP_STT_TRAIN_MNG.USE_YN IS '삭제여부';

-- 학습이력 인덱스 생성
create index IAAP_STT_TRAIN_MNG_IX0 on IAAP_STT_TRAIN_MNG (requested_at);
create index IAAP_STT_TRAIN_MNG_IX1 on IAAP_STT_TRAIN_MNG (result_model_id);
create index IAAP_STT_TRAIN_MNG_IX2 on IAAP_STT_TRAIN_MNG (service_model_id);
create index IAAP_STT_TRAIN_MNG_IX3 on IAAP_STT_TRAIN_MNG (updated_by);

-- 배포이력
CREATE TABLE IAAP_STT_DEPLOY_MNG
(
    ID                       NUMBER(11) NOT NULL,
    SERVICE_MODEL_ID         NUMBER(11) NOT NULL,
    DESCRIPTION              VARCHAR2(256),
    CREATED_BY               VARCHAR2(256) NOT NULL,
    REQUESTED_AT             DATE     NOT NULL,
    REG_DT                   DATE DEFAULT SYSDATE,
    REG_ID                   VARCHAR2(100) NOT NULL,
    REG_IP                   VARCHAR2(100) NOT NULL,
    UPD_DT                   DATE DEFAULT SYSDATE,
    UPD_ID                   VARCHAR2(100) NOT NULL,
    UPD_IP                   VARCHAR2(100) NOT NULL,
    RESULT_MODEL_ID          VARCHAR2(256) NOT NULL,
    RESULT_MODEL_DESCRIPTION VARCHAR2(256) NOT NULL,
    RESULT_MODEL_MODELTYPE   VARCHAR2(10),
    RESULT_CODE              VARCHAR2(100),
    RESULT_MSG               VARCHAR2(256),
    COMPLETED_AT             DATE,
    DURATION                 NUMBER(10),
    STATUS                   VARCHAR2(256),
    USE_YN                   VARCHAR2(2)   NOT NULL,
    SAVE_YN		VARCHAR2(1)   NOT NULL,
    DEPLOY_LIST              CLOB,
    DEPLOY_URL               VARCHAR2(100),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_DEPLOY_MNG IS '배포이력';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.ID IS '배포이력ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.SERVICE_MODEL_ID IS '서비스모델ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.CREATED_BY IS '작성자';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.REQUESTED_AT IS '배포일시';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.RESULT_MODEL_ID IS '결과모델ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.RESULT_MODEL_DESCRIPTION IS '결과모델설명';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.RESULT_MODEL_MODELTYPE IS '결과모델타입';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.RESULT_CODE IS '배포결과코드';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.RESULT_MSG IS '배포요청결과';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.COMPLETED_AT IS '배포완료일시';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.DURATION IS '소요시간';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.STATUS IS '배포상태';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.USE_YN IS '삭제여부';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.SAVE_YN IS '인식률 추이 포함 여부';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.DEPLOY_LIST IS 'SRU서버들의 배포 상태';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MNG.DEPLOY_URL IS '배포서버주소';

-- 배포이력 인덱스 생성
create index IAAP_STT_DEPLOY_MNG_IX0 on IAAP_STT_DEPLOY_MNG (created_by);
create index IAAP_STT_DEPLOY_MNG_IX1 on IAAP_STT_DEPLOY_MNG (requested_at);
create index IAAP_STT_DEPLOY_MNG_IX2 on IAAP_STT_DEPLOY_MNG (result_model_id);
create index IAAP_STT_DEPLOY_MNG_IX3 on IAAP_STT_DEPLOY_MNG (service_model_id);
create index IAAP_STT_DEPLOY_MNG_IX4 on IAAP_STT_DEPLOY_MNG (status);

-- 배포모델
CREATE TABLE IAAP_STT_DEPLOY_MODEL
(
    ID              NUMBER(11) NOT NULL,
    SERVICE_MODEL_ID NUMBER(11)NOT NULL,
    DESCRIPTION     VARCHAR2(256),
    UPLOADED_BY     VARCHAR2(256) NOT NULL,
    UPLOADED_DATE   DATE     NOT NULL,
    REG_DT          DATE DEFAULT SYSDATE,
    REG_ID          VARCHAR2(100) NOT NULL,
    REG_IP          VARCHAR2(100) NOT NULL,
    UPD_DT          DATE DEFAULT SYSDATE,
    UPD_ID          VARCHAR2(100) NOT NULL,
    UPD_IP          VARCHAR2(100) NOT NULL,
    RESULT_MODEL_ID VARCHAR2(256) NOT NULL,
    MODEL_PATH      VARCHAR2(256) NOT NULL,
    MODEL_AUTH_KEY  VARCHAR2(256) NOT NULL,
    DATA_NUM        NUMBER(11) NOT NULL,
    USE_YN          VARCHAR2(2)   NOT NULL,
    MODEL_TYPE      VARCHAR2(20),
    DATA_TIME      VARCHAR2(100),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_DEPLOY_MODEL IS '배포모델';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.ID IS '배포모델ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.SERVICE_MODEL_ID IS '서비스모델ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.UPLOADED_BY IS '작성자';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.UPLOADED_DATE IS '등록날짜';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.RESULT_MODEL_ID IS '결과모델ID';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.MODEL_PATH IS '모델경로';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.MODEL_AUTH_KEY IS 'MD5 hash checksum';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.DATA_NUM IS '학습데이터수';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.USE_YN IS '삭제여부';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.MODEL_TYPE IS '학습데이터의 모델타입';
COMMENT ON COLUMN IAAP_STT_DEPLOY_MODEL.DATA_TIME IS '음성데이터의 총 학습시간';

-- 배포모델 인덱스 생성
create index IAAP_STT_DEPLOY_MODEL_IX0 on IAAP_STT_DEPLOY_MODEL (result_model_id);
create index IAAP_STT_DEPLOY_MODEL_IX1 on IAAP_STT_DEPLOY_MODEL (service_model_id);
create index IAAP_STT_DEPLOY_MODEL_IX2 on IAAP_STT_DEPLOY_MODEL (uploaded_by);
create index IAAP_STT_DEPLOY_MODEL_IX3 on IAAP_STT_DEPLOY_MODEL (uploaded_date);

-- 단건테스트
CREATE TABLE IAAP_STT_TEST_DATA
(
    UUID         VARCHAR2(256) NOT NULL,
    RESULT_CODE  VARCHAR2(100) NOT NULL,
    RESULT_MSG   VARCHAR2(256) NOT NULL,
    SERVICE_CODE VARCHAR2(100) NOT NULL,
    STT_RESULT   CLOB         NOT NULL,
    REG_DT       DATE DEFAULT SYSDATE     NULL,
    PRIMARY KEY (UUID)
);

COMMENT ON TABLE IAAP_STT_TEST_DATA IS '단건테스트 임시 테이블';
COMMENT ON COLUMN IAAP_STT_TEST_DATA.UUID IS '단건테스트를 구분짓는 UUID';
COMMENT ON COLUMN IAAP_STT_TEST_DATA.RESULT_CODE IS '테스트결과코드';
COMMENT ON COLUMN IAAP_STT_TEST_DATA.RESULT_MSG IS '테스트요청결과';
COMMENT ON COLUMN IAAP_STT_TEST_DATA.SERVICE_CODE IS '서비스코드';
COMMENT ON COLUMN IAAP_STT_TEST_DATA.STT_RESULT IS '단건테스트 결과';
COMMENT ON COLUMN IAAP_STT_TEST_DATA.REG_DT IS '등록일자';

-- create index IAAP_STT_TEST_DATA_uuid_IDX on IAAP_STT_TEST_DATA (UUID);

CREATE TABLE IAAP_STT_STATISTICS
(
    RES_DATE_TIME      VARCHAR2(100) NOT NULL,
    SUPPORT_SVC_LIST   CLOB NOT NULL,
    COMPLETE_SVC_LIST  CLOB DEFAULT NULL,
    SERVICE_CODE       VARCHAR2(100) NOT NULL,
    REQUEST_COUNT      NUMBER(10) NOT NULL,
    COMPLETE_COUNT     NUMBER(10) NOT NULL,
    FAIL_COUNT         NUMBER(10) NOT NULL,
    BUSY_CALL_COUNT    NUMBER(10),
    SCU_NO             VARCHAR2(100) DEFAULT NULL,
    SERVER_NAME        VARCHAR2(100) NOT NULL,
    TOTAL_SERVER_CNT   NUMBER(10) NOT NULL,
    COMPLETE_SERVER_CNT NUMBER(10) NOT NULL,
    REG_DT     DATE DEFAULT SYSDATE,
    REG_ID     VARCHAR2(100) NOT NULL,
    REG_IP     VARCHAR2(100) NOT NULL,
    UPD_DT     DATE DEFAULT SYSDATE,
    UPD_ID     VARCHAR2(100) NOT NULL,
    UPD_IP     VARCHAR2(100) NOT NULL,
    USE_YN     VARCHAR2(2)   NOT NULL,
    PRIMARY KEY (SERVICE_CODE, RES_DATE_TIME, SERVER_NAME, REG_DT)
);

COMMENT ON TABLE IAAP_STT_STATISTICS IS 'STT 요청통계';
COMMENT ON COLUMN IAAP_STT_STATISTICS.RES_DATE_TIME IS '통계정보 응답 시간(분단위)';
COMMENT ON COLUMN IAAP_STT_STATISTICS.SUPPORT_SVC_LIST IS 'SCU에서 제공하는 SVC 목록';
COMMENT ON COLUMN IAAP_STT_STATISTICS.COMPLETE_SVC_LIST IS '통계 정보 조회를 성공한 svc 목록';
COMMENT ON COLUMN IAAP_STT_STATISTICS.SERVICE_CODE IS '서비스 코드명';
COMMENT ON COLUMN IAAP_STT_STATISTICS.REQUEST_COUNT IS 'STT 요청 건수';
COMMENT ON COLUMN IAAP_STT_STATISTICS.COMPLETE_COUNT IS 'STT 완료 건수';
COMMENT ON COLUMN IAAP_STT_STATISTICS.FAIL_COUNT IS 'STT 실패 건수';
COMMENT ON COLUMN IAAP_STT_STATISTICS.BUSY_CALL_COUNT IS 'STT 통화중 건수';
COMMENT ON COLUMN IAAP_STT_STATISTICS.SCU_NO IS 'SCU명';
COMMENT ON COLUMN IAAP_STT_STATISTICS.SERVER_NAME IS '서버명';
COMMENT ON COLUMN IAAP_STT_STATISTICS.TOTAL_SERVER_CNT IS 'C-POD 전체 개수';
COMMENT ON COLUMN IAAP_STT_STATISTICS.COMPLETE_SERVER_CNT IS 'STT 통계 정보 조회 성공한 C-POD개수';
COMMENT ON COLUMN IAAP_STT_STATISTICS.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_STATISTICS.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_STATISTICS.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_STATISTICS.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_STATISTICS.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_STATISTICS.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_STATISTICS.USE_YN IS '삭제여부';

CREATE TABLE IAAP_STT_STATISTICS_ERROR
(
    RES_DATE_TIME VARCHAR2(100) NOT NULL,
    SERVICE_CODE VARCHAR2(100) NOT NULL,
    SCU_NO         VARCHAR2(100) NOT NULL,
    REG_DT          DATE DEFAULT SYSDATE,
    REG_ID           VARCHAR2(100) NOT NULL,
    REG_IP           VARCHAR2(100) NOT NULL,
    UPD_DT         DATE DEFAULT SYSDATE,
    UPD_ID          VARCHAR2(100) NOT NULL,
    UPD_IP           VARCHAR2(100) NOT NULL,
    USE_YN          VARCHAR2(2)   NOT NULL,
    PRIMARY KEY (RES_DATE_TIME, SERVICE_CODE, SCU_NO, REG_DT)
);

COMMENT ON TABLE IAAP_STT_STATISTICS_ERROR IS 'STT 에러통계';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.RES_DATE_TIME IS '통계정보 응답 시간(분단위)';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.SERVICE_CODE IS '서비스 코드명';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.SCU_NO IS 'SCU명';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_STATISTICS_ERROR.USE_YN IS '삭제여부';

CREATE TABLE IAAP_STT_CONFIG
(
    ID                   NUMBER(11) NOT NULL,
    CODE_KEY   			 VARCHAR2(100) NOT NULL,
    CODE_VALUE         	 VARCHAR2(100) NOT NULL,
    DESCRIPTION          VARCHAR2(255),
    REG_DT               DATE     DEFAULT SYSDATE,
    REG_ID               VARCHAR2(60)  NOT NULL,
    REG_IP               VARCHAR2(23)  NOT NULL,
    UPD_DT               DATE     DEFAULT NULL,
    UPD_ID               VARCHAR2(60)  DEFAULT NULL,
    UPD_IP               VARCHAR2(23)  DEFAULT NULL,
    USE_YN               CHAR(1) DEFAULT 'Y'      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT IAAP_STT_CONFIG_UK UNIQUE (CODE_KEY,DESCRIPTION)
);

COMMENT ON TABLE IAAP_STT_CONFIG IS 'STT CONFIG정보 테이블';
COMMENT ON COLUMN IAAP_STT_CONFIG.ID IS 'CONFIG ID';
COMMENT ON COLUMN IAAP_STT_CONFIG.CODE_KEY IS '키값';
COMMENT ON COLUMN IAAP_STT_CONFIG.CODE_VALUE IS '설정값';
COMMENT ON COLUMN IAAP_STT_CONFIG.DESCRIPTION IS '설명';
COMMENT ON COLUMN IAAP_STT_CONFIG.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_STT_CONFIG.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_STT_CONFIG.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_STT_CONFIG.UPD_DT IS '수정일시';
COMMENT ON COLUMN IAAP_STT_CONFIG.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_STT_CONFIG.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_STT_CONFIG.USE_YN IS '사용여부';

CREATE TABLE IAAP_STT_CALL_INFO (
  STT_CALL_IDX NUMBER(10) NOT NULL ,
  APPLICATION_ID VARCHAR2(50) NOT NULL,
  REC_ID VARCHAR2(50) NOT NULL,
  CALL_ID VARCHAR2(50) NOT NULL,
  STT_ID VARCHAR2(50) NOT NULL,
  DEVICE_ID VARCHAR2(50) NOT NULL,
  SERVICE_CODE VARCHAR2(2) NOT NULL,
  CALL_STATUS VARCHAR2(4) NOT NULL,
  CALL_START_TIME DATE DEFAULT SYSDATE NOT NULL,
  CALL_END_TIME DATE DEFAULT SYSDATE NOT NULL,
  WAV_FILE_PATH VARCHAR2(500) NULL,
  PRIMARY KEY (STT_CALL_IDX)
);

COMMENT ON TABLE IAAP_STT_CALL_INFO IS '콜 정보 관리';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.STT_CALL_IDX IS '테이블 pk';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.APPLICATION_ID IS '상담어플리케이션 id';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.REC_ID IS '녹취 id';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.CALL_ID IS '콜 ID';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.STT_ID IS 'STT_ID';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.DEVICE_ID IS '요청 Client id';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.SERVICE_CODE IS '서비스 코드';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.CALL_STATUS IS '콜 상태';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.CALL_START_TIME IS '콜 시작시간';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.CALL_END_TIME IS '콜 종료시간';
COMMENT ON COLUMN IAAP_STT_CALL_INFO.WAV_FILE_PATH IS '음원파일 경로';

CREATE INDEX IAAP_STT_CALL_INFO_IX0 ON IAAP_STT_CALL_INFO (APPLICATION_ID);
CREATE INDEX IAAP_STT_CALL_INFO_IX1 ON IAAP_STT_CALL_INFO (REC_ID);
CREATE INDEX IAAP_STT_CALL_INFO_IX2 ON IAAP_STT_CALL_INFO (CALL_ID);
CREATE INDEX IAAP_STT_CALL_INFO_IX3 ON IAAP_STT_CALL_INFO (SERVICE_CODE);
CREATE INDEX IAAP_STT_CALL_INFO_IX4 ON IAAP_STT_CALL_INFO (CALL_STATUS);
CREATE INDEX IAAP_STT_CALL_INFO_IX5 ON IAAP_STT_CALL_INFO (CALL_START_TIME);
CREATE INDEX IAAP_STT_CALL_INFO_IX6 ON IAAP_STT_CALL_INFO (SERVICE_CODE, CALL_STATUS, CALL_START_TIME);

CREATE TABLE IAAP_STT_RESULT_INFO (
  STT_RESULT_IDX   	number(10) NOT NULL,
  STT_ID		  	varchar2(50) NOT NULL,
  SPEAKER_TYPE  	varchar2(2) NOT NULL,
  APPLICATION_ID	varchar2(50) NOT NULL,
  STT_SEQ			number(10),
  START_TIME_STAMP  number(10),
  END_TIME_STAMP    number(10),
  STT_JSON    		CLOB DEFAULT NULL,
  STT_TEXT    		CLOB DEFAULT NULL,
  CONFIDENCE    	varchar2(15) DEFAULT 0,
  EPD_START_TIME 	DATE DEFAULT SYSDATE,
  EPD_END_TIME 		DATE DEFAULT SYSDATE,
  PRIMARY KEY (STT_RESULT_IDX)
);

COMMENT ON TABLE IAAP_STT_RESULT_INFO IS 'STT 인식결과 관리';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.STT_RESULT_IDX IS '테이블 pk';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.STT_ID IS 'STT_ID';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.SPEAKER_TYPE IS '화자 구분  RX or TX';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.APPLICATION_ID IS '상담어플리케이션 id';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.STT_SEQ IS 'STT SEQ';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.START_TIME_STAMP IS '시작 타임스탬프';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.END_TIME_STAMP IS '종료 타임스탬프';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.STT_JSON IS 'stt JSON 인식결과';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.STT_TEXT IS 'stt 인식결과';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.CONFIDENCE IS 'STT 신뢰도 값';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.EPD_START_TIME IS 'EPD 발화 시작 시간';
COMMENT ON COLUMN IAAP_STT_RESULT_INFO.EPD_END_TIME IS 'EPD 발화 종료 시간';

CREATE INDEX IAAP_STT_RESULT_INFO_IX0 ON IAAP_STT_RESULT_INFO (APPLICATION_ID);

-- CREATE TABLE
CREATE TABLE IAAP_STT_ERROR_LOG
(
    ID           NUMBER(11) NOT NULL,
    TYPE         VARCHAR2(100) NOT NULL, /* 장애유형 : IF(인터페이스), SYSTEM(시스템) */
    ERROR_CODE   VARCHAR2(100),          /* IF 인 경우 장애 코드 */
    ERROR_MSG    VARCHAR2(100),          /* IF 인 경우 장애 메시지 */
    API_URL      VARCHAR2(500),			 /* IF 인 경우 요청 URL */
    SERVER_ID    VARCHAR2(200),			 /* SYSTEM 인 경우 서버ID */
    ERROR_POINT  VARCHAR2(1),			 /* SYSTEM 인 경우 모니터링 대상(C:CPU, M:MEMORY, S:STORAGE) */
    THRESHOLD    NUMBER(20),				 /* SYSTEM 인 경우 임계설정값 */
    STATUS_VALUE NUMBER(20), 			 /* SYSTEM 인 경우 상태값 */
    ERROR_TIME   DATE DEFAULT SYSDATE,   /* 장애발생시간 */
    PRIMARY KEY (ID)
);

COMMENT ON TABLE IAAP_STT_ERROR_LOG IS '장애이력';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.ID IS '장애이력 ID 시퀀스';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.TYPE IS '장애유형 : IF(인터페이스), SYSTEM(시스템)';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.ERROR_CODE IS 'IF 인 경우 장애 코드';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.ERROR_MSG IS 'IF 인 경우 장애 메시지';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.API_URL IS 'IF 인 경우 요청 URL';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.SERVER_ID IS 'SYSTEM 인 경우 서버ID';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.ERROR_POINT IS 'SYSTEM 인 경우 모니터링 대상';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.THRESHOLD IS 'SYSTEM 인 경우 임계설정값';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.STATUS_VALUE IS 'SYSTEM 인 경우 상태값';
COMMENT ON COLUMN IAAP_STT_ERROR_LOG.ERROR_TIME IS '장애발생시간';

CREATE INDEX IAAP_STT_ERROR_LOG_TYPE_IX0 ON IAAP_STT_ERROR_LOG (TYPE);

CREATE TABLE IAAP_STT_SYSTEM_STATUS
(
    ID                    NUMBER(19)       NOT NULL,
    SERVER_ID             VARCHAR2(200) NOT NULL,
    CPU_USED              NUMBER(10)          DEFAULT 0,
    MAX_MEMORY_SIZE       NUMBER(19)       DEFAULT 0,
    FREE_MEMORY_SIZE      NUMBER(19)       DEFAULT 0,
    MAX_APP_STORAGE_SIZE  NUMBER(19)       DEFAULT 0,
    FREE_APP_STORAGE_SIZE NUMBER(19)       DEFAULT 0,
    MAX_LOG_STORAGE_SIZE  NUMBER(19)       DEFAULT 0,
    FREE_LOG_STORAGE_SIZE NUMBER(19)       DEFAULT 0,
    BPS                   NUMBER(19)       DEFAULT 0,
    PPS                   NUMBER(19)       DEFAULT 0,
    LAST_CHECK_TIME       TIMESTAMP     NOT NULL,
    REG_DT      TIMESTAMP                               DEFAULT NULL,
    REG_ID      VARCHAR2(60) DEFAULT NULL,
    REG_IP      VARCHAR2(23) DEFAULT NULL,
    PRIMARY KEY (ID, LAST_CHECK_TIME),
    CONSTRAINT IAAP_STT_SYSTEM_STATUS_UK UNIQUE (SERVER_ID, LAST_CHECK_TIME)
)
PARTITION BY RANGE (LAST_CHECK_TIME) (
        PARTITION IAAP_STT_SYSTEM_STATUS_202309 VALUES LESS THAN ('2023-10-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202310 VALUES LESS THAN ('2023-11-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202311 VALUES LESS THAN ('2023-12-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202312 VALUES LESS THAN ('2024-01-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202401 VALUES LESS THAN ('2024-02-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202402 VALUES LESS THAN ('2024-03-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202403 VALUES LESS THAN ('2024-04-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202404 VALUES LESS THAN ('2024-05-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202405 VALUES LESS THAN ('2024-06-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202406 VALUES LESS THAN ('2024-07-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202407 VALUES LESS THAN ('2024-08-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202408 VALUES LESS THAN ('2024-09-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202409 VALUES LESS THAN ('2024-10-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202410 VALUES LESS THAN ('2024-11-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202411 VALUES LESS THAN ('2024-12-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202412 VALUES LESS THAN ('2025-01-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202501 VALUES LESS THAN ('2025-02-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202502 VALUES LESS THAN ('2025-03-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202503 VALUES LESS THAN ('2025-04-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202504 VALUES LESS THAN ('2025-05-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202505 VALUES LESS THAN ('2025-06-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202506 VALUES LESS THAN ('2025-07-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202507 VALUES LESS THAN ('2025-08-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202508 VALUES LESS THAN ('2025-09-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202509 VALUES LESS THAN ('2025-10-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202510 VALUES LESS THAN ('2025-11-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202511 VALUES LESS THAN ('2025-12-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202512 VALUES LESS THAN ('2026-01-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202601 VALUES LESS THAN ('2026-02-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202602 VALUES LESS THAN ('2026-03-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202603 VALUES LESS THAN ('2026-04-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202604 VALUES LESS THAN ('2026-05-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202605 VALUES LESS THAN ('2026-06-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202606 VALUES LESS THAN ('2026-07-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202607 VALUES LESS THAN ('2026-08-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202608 VALUES LESS THAN ('2026-09-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202609 VALUES LESS THAN ('2026-10-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202610 VALUES LESS THAN ('2026-11-01 00:00:00'),
        PARTITION IAAP_STT_SYSTEM_STATUS_202611 VALUES LESS THAN ('2026-12-01 00:00:00'),
        PARTITION PMAXVALUES VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX IAAP_STT_SYSTEM_STATUS_IX0 ON IAAP_STT_SYSTEM_STATUS (LAST_CHECK_TIME);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE IAAP_STT_SYSTEM_STATUS_STATH
(
    DATE_HOUR    VARCHAR2(20) NOT NULL,
    SERVER_ID    VARCHAR2(200) NOT NULL,
    CPU_MX       NUMBER(10)          DEFAULT 0,
    CPU_MN       NUMBER(10)          DEFAULT 0,
    CPU_AV       NUMBER(10)          DEFAULT 0,
    MEM_TT       NUMBER(19)       DEFAULT 0,
    MEM_MX       NUMBER(19)       DEFAULT 0,
    MEM_MN       NUMBER(19)       DEFAULT 0,
    MEM_AV       NUMBER(19)       DEFAULT 0,
    STR_TT       NUMBER(19)       DEFAULT 0,
    STR_MX       NUMBER(19)       DEFAULT 0,
    STR_MN       NUMBER(19)       DEFAULT 0,
    STR_AV       NUMBER(19)       DEFAULT 0,
    LOG_TT       NUMBER(19)       DEFAULT 0,
    LOG_MX       NUMBER(19)       DEFAULT 0,
    LOG_MN       NUMBER(19)       DEFAULT 0,
    LOG_AV       NUMBER(19)       DEFAULT 0,
    BPS_MX       NUMBER(19)       DEFAULT 0,
    BPS_MN       NUMBER(19)       DEFAULT 0,
    BPS_AV       NUMBER(19)       DEFAULT 0,
    PPS_MX       NUMBER(19)       DEFAULT 0,
    PPS_MN       NUMBER(19)       DEFAULT 0,
    PPS_AV       NUMBER(19)       DEFAULT 0,
    PRIMARY KEY (DATE_HOUR, SERVER_ID)
);

COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.DATE_HOUR IS '통계시간';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.SERVER_ID IS '서버의 hostname';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.CPU_MX IS 'CPU사용율 최대';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.CPU_MN IS 'CPU사용율 최소';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.CPU_AV IS 'CPU사용율 평균';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.MEM_TT IS '물리 메모리 사이즈 (mbyte) total';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.MEM_MX IS 'Free 물리 메모리 사이즈 (mbyte) 최대';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.MEM_MN IS 'Free 물리 메모리 사이즈 (mbyte) 최소';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.MEM_AV IS 'Free 물리 메모리 사이즈 (mbyte) 평균';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.STR_TT IS 'App 파티션의 디스크 사이즈 (mbyte) total';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.STR_MX IS 'Free App 파티션의 디스크 사이즈 (mbyte) 최대';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.STR_MN IS 'Free App 파티션의 디스크 사이즈 (mbyte) 최소';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.STR_AV IS 'Free App 파티션의 디스크 사이즈 (mbyte) 평균';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.LOG_TT IS '로그 파티션의 디스크 사이즈 (mbyte) total';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.LOG_MX IS 'Free 로그 파티션의 디스크 사이즈 (mbyte) 최대';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.LOG_MN IS 'Free 로그 파티션의 디스크 사이즈 (mbyte) 최소';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.LOG_AV IS 'Free 로그 파티션의 디스크 사이즈 (mbyte) 평균';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.BPS_MX IS '초당 송/수신 bit 수  (단위 kbps) 최대';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.BPS_MN IS '초당 송/수신 bit 수  (단위 kbps) 최소';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.BPS_AV IS '초당 송/수신 bit 수  (단위 kbps) 평균';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.PPS_MX IS '초당 송/수신 packet 수 (단위 pps) 최대';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.PPS_MN IS '초당 송/수신 packet 수 (단위 pps) 최소';
COMMENT ON COLUMN IAAP_STT_SYSTEM_STATUS_STATH.PPS_AV IS '초당 송/수신 packet 수 (단위 pps) 평균'; 

CREATE INDEX IAAP_STT_SYSTEM_STATUSH_IX0 ON IAAP_STT_SYSTEM_STATUS_STATH (DATE_HOUR);

CREATE TABLE "IAAP_STT_TRAIN_DATASET" 
(	
   "AM_DATASET_ID" NUMBER(10,0) NOT NULL, 
	"SERVICE_MODEL" VARCHAR2(20), 
	"SERVICE_MODEL_ID" NUMBER(11,0), 
	"DATASET_NAME" VARCHAR2(50), 
	"TRAIN_TIME" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(100), 
	"REG_DT" DATE DEFAULT current_date NOT NULL, 
	"REG_ID" VARCHAR2(60) NOT NULL, 
	"REG_IP" VARCHAR2(23) NOT NULL, 
	"UPD_DT" DATE, 
	"UPD_ID" VARCHAR2(60), 
	"UPD_IP" VARCHAR2(23), 
	"USE_YN" CHAR(1) DEFAULT 'Y' NOT NULL, 
	"DIRECTORY_ID" NUMBER(11,0) NOT NULL,
	PRIMARY KEY (AM_DATASET_ID)
);

   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."AM_DATASET_ID" IS 'AM학습데이터셋 ID';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."SERVICE_MODEL" IS '서비스모델';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."SERVICE_MODEL_ID" IS '서비스모델ID';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."DATASET_NAME" IS '데이터셋이름';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."TRAIN_TIME" IS '학습시간';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."DESCRIPTION" IS '설명';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."REG_DT" IS '등록일시';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."REG_ID" IS '등록자ID';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."REG_IP" IS '등록자IP';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."UPD_DT" IS '수정일시';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."UPD_ID" IS '수정자ID';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."UPD_IP" IS '수정자IP';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "IAAP_STT_TRAIN_DATASET"."DIRECTORY_ID" IS 'NAS디렉토리 메뉴에서의 디렉토리ID값';
   COMMENT ON TABLE "IAAP_STT_TRAIN_DATASET"  IS 'STT AM 학습데이터셋 관리';


-- CREATE SEQ
CREATE SEQUENCE SEQ_IAAP_STT_TRAIN_DATA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_TRAIN_AM_DATA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_SERVICE_MODEL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_ENGINE_URL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_VERIFY_DATASET START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_VERIFY_DATA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_VERIFY_HISTORY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_DICTATION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_USAGE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_DEPLOY_MODEL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_DEPLOY_MNG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_TRAIN_MNG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_CONFIG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_CALL_INFO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_RESULT_INFO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_ERROR_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_SYSTEM_STATUS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_IAAP_STT_TRAIN_DATASET START WITH 1 INCREMENT BY 1;

-- 환경설정 정보 세팅 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

-- 환경변수 카테고리 생성
INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'C'
	, '삭제 스케줄러'
	, 'CATEGORY_SCHEDULER'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'C'
	, 'HW 리소스 임계치'
	, 'CATEGORY_THRESHOLD'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'C'
	, '에이전트'
	, 'CATEGORY_AGENT'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'C'
	, '기타 설정'
	, 'CATEGORY_ETC'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);


-- 초기데이터 생성
INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'Y'
	, 'SCHEDULER_USEYN'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, '0'
	, 'SCEDULER_CYCLE_HWRESOURCE'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, '0'
	, 'SCHEDULER_CYCLE_STATISTICS'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, '0'
	, 'REMOVER_STANDARD'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, '0'
	, 'REMOVER_TIME'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

/* ---------------------------- */
/* 			삭제할 데이터 			*/
/* ---------------------------- */

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_AM_TRAIN_DATA'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_LM_TRAIN_DATA'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_TRAIN_MNG'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_VERIFY_DATA'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_VERIFY_MNG'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_DEPLOY_MODEL'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_DEPLOY_MNG'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_CALLINFO'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_STT_RESULT'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_HW_RESOURCE'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_STATISTICS'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_DATA_TEST'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

/* ---------------------------- */
/* 			삭제할 파일 			*/
/* ---------------------------- */

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_FILE_AM_TRAIN_DATA'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_FILE_DEPLOY_MODEL'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_FILE_VERIFY_DATA'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_FILE_CALLINFO'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'S'
	, 'N'
	, 'REMOVER_FILE_TEST'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

/* ---------------------------- */
/* 		  HW 리소스 임계치  		*/
/* ---------------------------- */
INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'T'
	, '0'
	, 'THRESHOLD_CPU'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'T'
	, '0'
	, 'THRESHOLD_MEMORY'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'T'
	, '0'
	, 'THRESHOLD_STORAGE'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);




/* ---------------------------- */
/* 			AGENT 설정	 		*/
/* ---------------------------- */
INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'A'
	, 'N'
	, 'MULTIPART_SUB_TEST'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'A'
	, 'N'
	, 'MULTIPART_SUB_DEPLOY'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'A'
	, 'N'
	, 'MULTIPART_HOST_TEST'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'A'
	, 'N'
	, 'MULTIPART_HOST_DEPLOY'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY
	, CODE_VALUE
	, DESCRIPTION
	, REG_DT
	, REG_ID
	, REG_IP
	, UPD_DT
	, UPD_ID
	, UPD_IP
	, USE_YN
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'A'
	, 'host'
	, 'SESSION_TARGET'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y');
	
/* ---------------------------- */
/* 			암호화 설정	 			*/
/* ---------------------------- */
INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'P'
	, 'N'
	, 'TEXT_ENCRYPT'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'P'
	, 'N'
	, 'WAV_ENCRYPT'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

/* ---------------------------- */
/* 			기타 설정	 			*/
/* ---------------------------- */
INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'E'
	, '10'
	, 'SCREEN_RECORDS'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);

INSERT INTO IAAP_STT_CONFIG(
	ID
	, CODE_KEY 
	, CODE_VALUE 
	, DESCRIPTION 
	, REG_DT 
	, REG_ID
	, REG_IP 
	, UPD_DT 
	, UPD_ID 
	, UPD_IP 
	, USE_YN 
) VALUES(
	SEQ_IAAP_STT_CONFIG.NEXTVAL
	, 'E'
	, '0'
	, 'CONFIDENCE_CHART_THRESHOLD'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, CURRENT_DATE
	, 'test'
	, 'test'
	, 'Y'
);