/*
alter session set "_ORACLE_SCRIPT"=true;
create user smp_master@ identified by admin;
grant RESOURCE, CONNECT, DBA to smp_master@;

DROP SEQUENCE SEQ_IAAP_SERVICE_CONFIG;
DROP TABLE IAAP_SERVICE_CONFIG;
DROP TABLE shedlock;
*/

CREATE SEQUENCE SEQ_IAAP_SERVICE_CONFIG START WITH 1 INCREMENT BY 1;

CREATE TABLE IAAP_SERVICE_CONFIG
(
    ID                    NUMBER(11)    NOT NULL primary key,
    SITE_CODE             VARCHAR2(100) NOT NULL,
    PROJECT_CODE          VARCHAR2(100) NOT NULL,
    ENGINE_PARAMETER      VARCHAR2(100) NOT NULL,
    DB_DRIVER_CLASS_NAME  VARCHAR2(100) NOT NULL,
    DB_URL                VARCHAR2(500) NOT NULL,
    DB_USERNAME           VARCHAR2(100) NOT NULL,
    DB_PASSWORD           VARCHAR2(100) NOT NULL,
    SMP_TYPE              VARCHAR2(100) ,
    IS_DEFAULT            VARCHAR2(1)   DEFAULT 'N',
    REG_DT                DATE          DEFAULT CURRENT_TIMESTAMP,
    REG_ID                VARCHAR2(100) NOT NULL,
    REG_IP                VARCHAR2(100) NOT NULL,
    UPD_DT                DATE          DEFAULT CURRENT_TIMESTAMP,
    UPD_ID                VARCHAR2(100) NOT NULL,
    UPD_IP                VARCHAR2(100) NOT NULL,
    USE_YN                VARCHAR2(1)   DEFAULT 'Y'
);

COMMENT ON TABLE IAAP_SERVICE_CONFIG IS '서비스 연동 정보';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.ID IS '서비스 설정 ID';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.SITE_CODE IS '사이트 코드';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.PROJECT_CODE IS '프로젝트 코드';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.ENGINE_PARAMETER IS '엔진 파라미터';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.DB_DRIVER_CLASS_NAME IS 'DB 드라이버 클래스명';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.DB_URL IS 'DB URL';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.DB_USERNAME IS 'DB 사용자ID';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.DB_PASSWORD IS 'DB 비밀번호';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.SMP_TYPE IS 'SMP TYPE';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.IS_DEFAULT IS '기본 설정 여부';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.REG_DT IS '등록일자';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.REG_ID IS '등록자 ID';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.REG_IP IS '등록자 IP';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.UPD_DT IS '수정일자';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.UPD_ID IS '수정자 ID';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.UPD_IP IS '수정자 IP';
COMMENT ON COLUMN IAAP_SERVICE_CONFIG.USE_YN IS '사용여부';

CREATE TABLE shedlock (
  NAME VARCHAR2(64) NOT NULL,
  LOCK_UNTIL TIMESTAMP DEFAULT NULL,
  LOCKED_AT TIMESTAMP DEFAULT NULL,
  LOCKED_BY VARCHAR2(255) DEFAULT NULL,
  PRIMARY KEY (NAME)
);
COMMENT ON TABLE shedlock IS '스케줄잠금처리 위한 관리';
COMMENT ON COLUMN shedlock.NAME IS '스케줄잠금이름';
COMMENT ON COLUMN shedlock.LOCK_UNTIL IS '잠금기간';
COMMENT ON COLUMN shedlock.LOCKED_AT IS '잠금일시';
COMMENT ON COLUMN shedlock.LOCKED_BY IS '잠금신청자';


/* for stt mater database */
INSERT INTO IAAP_SERVICE_CONFIG
	(ID, SITE_CODE, PROJECT_CODE, ENGINE_PARAMETER
	, DB_DRIVER_CLASS_NAME, DB_URL, DB_USERNAME, DB_PASSWORD
	, IS_DEFAULT, REG_ID, REG_IP, UPD_ID, UPD_IP)
VALUES(SEQ_IAAP_SERVICE_CONFIG.NEXTVAL, 'SITE', 'PROJECT', 'ENGINE'
	, 'oracle.jdbc.driver.OracleDriver', 'jdbc:oracle:thin:@localhost:1521:ORCL', 'smp_master', 'x+CJdjpWw3eXDf3QH4Xqog=='
	, 'Y', 'ID', '127.0.0.1', 'DT', '127.0.0.1');

INSERT INTO IAAP_SERVICE_CONFIG
	(ID, SITE_CODE, PROJECT_CODE, ENGINE_PARAMETER
	, DB_DRIVER_CLASS_NAME, DB_URL, DB_USERNAME, DB_PASSWORD
	, IS_DEFAULT, REG_ID, REG_IP, UPD_ID, UPD_IP)
VALUES(SEQ_IAAP_SERVICE_CONFIG.NEXTVAL, 'test-site-code', 'test-project-code', 'ENGINE'
	, 'oracle.jdbc.driver.OracleDriver', 'jdbc:oracle:thin:@localhost:1521:ORCL', 'smp_master', 'x+CJdjpWw3eXDf3QH4Xqog=='
	, 'N', 'ID', '127.0.0.1', 'DT', '127.0.0.1');