-- DROP SEQ
BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECORDS_REC';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -2289 THEN
			RAISE;
		END IF;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECORDS_STT';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -2289 THEN
			RAISE;
		END IF;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECORDS_STT_STATUS';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -2289 THEN
			RAISE;
		END IF;
END;

-- DROP TABLE
BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE RECORDS_REC';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE RECORDS_STT';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE RECORDS_STT_STATUS';
EXCEPTION
	WHEN OTHERS THEN
		IF SQLCODE != -942 THEN
			RAISE;
		END IF;
END;


-- CREATE TABLE
CREATE TABLE RECORDS_REC 
   (	
    RECORDS_REC_ID NUMBER(10,0) NOT NULL, 
	APPLICATION_ID VARCHAR2(20) NOT NULL, 
	REC_ID VARCHAR2(20) NOT NULL, 
	CALL_ID VARCHAR2(20) NOT NULL, 
	DESCRIPTION VARCHAR2(255) NOT NULL, 
	FILE_NAME VARCHAR2(255) NOT NULL, 
	STT_RESULTS CLOB NOT NULL, 
	STATUS VARCHAR2(4), 
	REC_STARTTIME TIMESTAMP (6) DEFAULT SYSDATE, 
	REC_ENDTIME TIMESTAMP (6) DEFAULT SYSDATE, 
	REC_TYPE VARCHAR2(1), 
	PRIMARY KEY (RECORDS_REC_ID));

COMMENT ON TABLE RECORDS_REC IS '준실시간 녹취 요청';
COMMENT ON COLUMN RECORDS_REC.RECORDS_REC_ID IS '인덱스';
COMMENT ON COLUMN RECORDS_REC.APPLICATION_ID IS '상담어플리케이션 ID';
COMMENT ON COLUMN RECORDS_REC.REC_ID IS '녹취 ID';
COMMENT ON COLUMN RECORDS_REC.CALL_ID IS '콜 ID';
COMMENT ON COLUMN RECORDS_REC.DESCRIPTION IS '파일 설명';
COMMENT ON COLUMN RECORDS_REC.FILE_NAME IS '파일명';
COMMENT ON COLUMN RECORDS_REC.STT_RESULTS IS 'STT 인식 결과';
COMMENT ON COLUMN RECORDS_REC.STATUS IS '파일 처리 상태 (1000: ready(요청상태), 2000 : STT 변환중, 3000 : STT 변환완료, 4000 : STT 변환실패, 5000 : 전송 완료 (암호화 음원, 메타파일), 6000 : 전송 실패 (암호화 음원, 메타파일))';
COMMENT ON COLUMN RECORDS_REC.REC_STARTTIME IS '녹취 시작 시간';
COMMENT ON COLUMN RECORDS_REC.REC_ENDTIME IS '녹취 종료 시간';
COMMENT ON COLUMN RECORDS_REC.REC_TYPE IS '요청 유형 1 : 녹취화면 단건변환 요청,  2 : SMP 수동 재처리 요청, 3 : SMP 전일 오류건 자동 재처리';

CREATE TABLE RECORDS_STT
   (	
    RECORDS_STT_IDX NUMBER(10,0) NOT NULL, 
	STT_ID VARCHAR2(30) NOT NULL, 
	APPLICATION_ID VARCHAR2(20) NOT NULL, 
	STT_SEQ number(10,0) NOT NULL, 
	START_SEQ number(10,0) NOT NULL, 
	END_SEQ number(10,0) NOT NULL, 
	SPEAKER_TYPE VARCHAR2(2) NOT NULL, 
	STT_RESULTS VARCHAR2(4000), 
	PRIMARY KEY (RECORDS_STT_IDX)
	);

COMMENT ON TABLE RECORDS_STT IS '실시간 STT';
COMMENT ON COLUMN RECORDS_STT.RECORDS_STT_IDX IS '인덱스';
COMMENT ON COLUMN RECORDS_STT.STT_ID IS 'STT ID';
COMMENT ON COLUMN RECORDS_STT.APPLICATION_ID IS '상담어플리케이션 ID';
COMMENT ON COLUMN RECORDS_STT.STT_SEQ IS 'STT SEQ';
COMMENT ON COLUMN RECORDS_STT.START_SEQ IS '시작 타임스탬프';
COMMENT ON COLUMN RECORDS_STT.END_SEQ IS '종료 타임스탬프';
COMMENT ON COLUMN RECORDS_STT.SPEAKER_TYPE IS '화자 구분';
COMMENT ON COLUMN RECORDS_STT.STT_RESULTS IS 'STT 인식 결과';

CREATE TABLE RECORDS_STT_STATUS 
   (	
    STT_ID VARCHAR2(30) NOT NULL, 
	REC_ID VARCHAR2(20) NOT NULL, 
	APPLICATION_ID VARCHAR2(20), 
	CALL_ID VARCHAR2(20), 
	CALL_STATUS VARCHAR2(4), 
	CALL_STARTTIME TIMESTAMP (6) DEFAULT SYSDATE, 
	CALL_ENDTIME TIMESTAMP (6) DEFAULT SYSDATE, 
	 PRIMARY KEY (STT_ID)
	);

COMMENT ON TABLE RECORDS_STT_STATUS IS '실시간 콜상태';
COMMENT ON COLUMN RECORDS_STT_STATUS.STT_ID IS 'STT ID';
COMMENT ON COLUMN RECORDS_STT_STATUS.REC_ID IS '녹취 ID';
COMMENT ON COLUMN RECORDS_STT_STATUS.APPLICATION_ID IS '상담어플리케이션 ID';
COMMENT ON COLUMN RECORDS_STT_STATUS.CALL_ID IS '콜 ID';
COMMENT ON COLUMN RECORDS_STT_STATUS.CALL_STATUS IS '콜 상태 1000:Start, 2000: Progress, 3000: End';
COMMENT ON COLUMN RECORDS_STT_STATUS.CALL_STARTTIME IS '콜 시작 시간';
COMMENT ON COLUMN RECORDS_STT_STATUS.CALL_ENDTIME IS '콜 종료 시간';

-- CREATE SEQ
CREATE SEQUENCE SEQ_RECORDS_REC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECORDS_STT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECORDS_STT_STATUS START WITH 1 INCREMENT BY 1;