-- CREATE TABLE
CREATE TABLE RECORDS_REC 
   (	
    RECORDS_REC_ID BIGINT NOT NULL COMMENT '인덱스', 
	APPLICATION_ID VARCHAR(20) NOT NULL COMMENT '상담어플리케이션 ID', 
	REC_ID VARCHAR(20) NOT NULL COMMENT '녹취 ID', 
	CALL_ID VARCHAR(20) NOT NULL COMMENT '콜 ID', 
	DESCRIPTION VARCHAR(255) NOT NULL COMMENT '파일 설명', 
	FILE_NAME VARCHAR(255) NOT NULL COMMENT '파일명', 
	STT_RESULTS LONGTEXT NOT NULL COMMENT 'STT 인식 결과', 
	STATUS VARCHAR(4) COMMENT '파일 처리 상태 (1000: ready(요청상태), 2000 : STT 변환중, 3000 : STT 변환완료, 4000 : STT 변환실패, 5000 : 전송 완료 (암호화 음원, 메타파일), 6000 : 전송 실패 (암호화 음원, 메타파일))', 
	REC_STARTTIME DATETIME (6) DEFAULT SYSDATE() COMMENT '녹취 시작 시간', 
	REC_ENDTIME DATETIME (6) DEFAULT SYSDATE() COMMENT '녹취 종료 시간', 
	REC_TYPE VARCHAR(1) COMMENT '요청 유형 1 : 녹취화면 단건변환 요청,  2 : SMP 수동 재처리 요청, 3 : SMP 전일 오류건 자동 재처리', 
	PRIMARY KEY (RECORDS_REC_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '준실시간 녹취 요청';

CREATE TABLE RECORDS_STT
   (	
    RECORDS_STT_IDX BIGINT NOT NULL COMMENT '인덱스', 
	STT_ID VARCHAR(30) NOT NULL COMMENT 'STT ID', 
	APPLICATION_ID VARCHAR(20) NOT NULL COMMENT '상담어플리케이션 ID', 
	STT_SEQ bigint NOT NULL COMMENT 'STT SEQ', 
	START_SEQ bigint NOT NULL COMMENT '시작 타임스탬프', 
	END_SEQ bigint NOT NULL COMMENT '종료 타임스탬프', 
	SPEAKER_TYPE VARCHAR(2) NOT NULL COMMENT '화자 구분', 
	STT_RESULTS VARCHAR(4000) COMMENT 'STT 인식 결과', 
	PRIMARY KEY (RECORDS_STT_IDX)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '실시간 STT';

CREATE TABLE RECORDS_STT_STATUS 
   (	
    STT_ID VARCHAR(30) NOT NULL COMMENT 'STT ID', 
	REC_ID VARCHAR(20) NOT NULL COMMENT '녹취 ID', 
	APPLICATION_ID VARCHAR(20) COMMENT '상담어플리케이션 ID', 
	CALL_ID VARCHAR(20) COMMENT '콜 ID', 
	CALL_STATUS VARCHAR(4) COMMENT '콜 상태 1000:Start, 2000: Progress, 3000: End', 
	CALL_STARTTIME DATETIME (6) DEFAULT SYSDATE() COMMENT '콜 시작 시간', 
	CALL_ENDTIME DATETIME (6) DEFAULT SYSDATE() COMMENT '콜 종료 시간', 
	 PRIMARY KEY (STT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT '실시간 콜상태';

-- CREATE SEQ
CREATE SEQUENCE SEQ_RECORDS_REC START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECORDS_STT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RECORDS_STT_STATUS START WITH 1 INCREMENT BY 1;